export {default as Loader} from './Loader';
export {default as Homepage} from './Homepage';
export {default as Navbar} from './Navbar';
export {default as Welcome} from './Welcome';
export {default as Services} from './Services';
export {default as Transactions} from './Transactions/LatestTransactions';
export {default as TransactionsHistory} from './Transactions/TransactionsHistory';
export {default as Market} from './Cryptocurrencies/Market';
export {default as Cryptocurrencies} from './Cryptocurrencies/Cryptocurrencies';
export {default as CryptoDetails} from './Cryptocurrencies/CryptoDetails.jsx';
export {default as News} from './Cryptocurrencies/News';
export {default as Footer} from './Footer';
export {default as Blogs} from "./Blogs"
